### ISSUE TITLE
Upgrade ActiveSupport version to 5+?

### ISSUE THREAD

**Issue by abevoelker** [github/pages-gem#547]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects
- [ ] The site generated by GitHub Pages
- [x] Building sites locally

### What did you do (e.g., steps to reproduce)
Added [jekyll-assets gem](https://github.com/envygeeks/jekyll-assets) to my project and used an `{% asset %}` liquid tag

### What did you expect to happen?
My site to build

### What happened instead?
```console
$ bundle exec jekyll serve --trace
Configuration file: /tmp/foo/_config.yml
            Source: /tmp/foo
       Destination: /tmp/foo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT in /tmp/foo/_posts/2018-03-27-welcome-to-jekyll.markdown
bundler: failed to load command: jekyll (/home/abe/.gem/ruby/2.5.0/bin/jekyll)
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:103:in `join'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:103:in `render'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:123:in `render_liquid'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:76:in `render_document'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:62:in `run'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:462:in `block (2 levels) in render_docs'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:460:in `each'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:460:in `block in render_docs'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:459:in `each_value'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:459:in `render_docs'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:190:in `render'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:73:in `process'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `block in start'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `each'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `start'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /home/abe/.gem/ruby/2.5.0/bin/jekyll:23:in `load'
  /home/abe/.gem/ruby/2.5.0/bin/jekyll:23:in `<top (required)>'
```

### Additional information
I originally filed an issue with jekyll-assets: envygeeks/jekyll-assets#522

The bug seems due to jekyll-assets using ActiveSupport 5+ while GH pages gems are still using 4.2... any chance GH pages can upgrade the ActiveSupport version?

**Comment by benbalter** [comment]
@abevoelker From the [project goals](https://github.com/github/pages-gem#project-goals):

> The goal of the GitHub Pages gem is to help GitHub Pages users bootstrap and maintain a Jekyll build environment that most closely matches the GitHub pages build environment. The GitHub Pages gem relies on explicit requirements shared between both users' computers and the build servers to ensure that the result of a user's local build is consistently also the result of the server's build.

Since Jekyll Assets is not currently a supported plugin on GitHub Pages, I'm afraid incompatibility with this Gem is beyond the scope of the project and not something we can support at this time.

**Comment by abevoelker** [comment]
I understand, thank you for your consideration. I'll switch to vanilla Jekyll then.
