### ISSUE TITLE
NoMethodError: undefined method `inflate' for Gem:Module

### ISSUE THREAD

**Issue by psquared-dev** [github/pages-gem#883]
After cloning a jekyll template. I run `bundle` command.

 I get the following error.

```bash
Error details

    NoMethodError: undefined method `inflate' for Gem:Module
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/fetcher.rb:87:in `fetch_spec'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/remote_specification.rb:71:in `_remote_specification'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/remote_specification.rb:76:in `method_missing'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:158:in `block in __dependencies'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:155:in `each'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:155:in `__dependencies'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:116:in `activate_platform'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:274:in `block in search_for'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:274:in `each'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:274:in `search_for'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:327:in `block in verify_gemfile_dependencies_are_found!'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `each'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `verify_gemfile_dependencies_are_found!'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:198:in `start'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:182:in `resolve'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/x/gems/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/x/gems/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/x/gems/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/x/gems/bin/bundle:25:in `load'
      /home/x/gems/bin/bundle:25:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  3.3.5
    Ruby      3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-linux-gnu]
    GEM_HOME  /home/x/gems
    GEM_PATH  
    Git       2.34.1
--- TEMPLATE END ----------------------------------------------------------------

```

**Comment by parkr** [comment]
Your bundler version is very old. Try:

`gem install bundler` to get v2 and retry.
