### ISSUE TITLE
Error: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0

### ISSUE THREAD

**Issue by xinbenlv** [github/pages-gem#899]
### Before submitting an issue, please be sure to

- [X] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [X] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)
```
bundle exec jekyll serve
```

### What did you expect to happen?

Successfully run local instance

### What happened instead?

```
❯
bundle exec jekyll serve
/Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll.rb:28: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-3.9.3 to add csv into its gemspec.
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
jekyll 3.9.3 | Error:  undefined method `[]' for nil
/Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/log_adapter.rb:43:in `adjust_verbosity'
	from /Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/configuration.rb:157:in `config_files'
	from /Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll.rb:113:in `configuration'
	from /Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/command.rb:43:in `configuration_from_options'
	from /Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:89:in `start'
	from /Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /Users/zzn/.gem/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/zzn/.gem/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/zzn/.gem/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/zzn/.gem/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/zzn/.gem/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/zzn/.gem/ruby/3.3.0/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
	from /Users/zzn/.gem/ruby/3.3.0/bin/jekyll:25:in `load'
	from /Users/zzn/.gem/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/zzn/.rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
	from /Users/zzn/.rubies/ruby-3.3.0/bin/bundle:25:in `load'
	from /Users/zzn/.rubies/ruby-3.3.0/bin/bundle:25:in `<main>'
```

### Additional information

* Link to the live site (if applicable):

https://b.zzn.im

* Link to the source repo (if applicable):

https://github.com/xinbenlv/zThink

**Comment by parkr** [comment]
This gem is not compatible with Ruby 3.3. Please downgrade. 

A fix for Jekyll 3 is proposed: https://github.com/github/pages-gem/pull/897

**Comment by janbrasna** [comment]
Both Ruby 3.3 and Jekyll 3.10 was added in v232, can you still reproduce even with the latest version?
